### ISSUE TITLE
Oracle JDBC drivers have new groupIds and artifactIds

### ISSUE THREAD

**Issue by aalmiray** [sproket/Persism#3]
The Oracle JDBC drivers have been updated and published to Maven Central since September 2019 starting with version `19.6.0.0`. The new coordinates use `com.oracle.database.jdbc` as base gorupId

https://mvnrepository.com/artifact/com.oracle.database.jdbc

**Comment by sproket** [comment]
Oh thanks. Yeah I was usually using a downloaded driver for ANT. I'm using an older version. But yeah, at some point I'll update my oracle test database. My plan is to move all my test DBs to Linux on a virtual box image and make it available somewhere for people.

**Comment by sproket** [comment]
My test DB is older 11g express edition. Do you know which dependency should I use?  Maybe I need to upgrade that version.

**Comment by sproket** [comment]
Thanks. Since my DB version is older. I just manually installed ojdbc6.jar - I added the file to libs and added a readme for it.

**Comment by dstango** [comment]
Actually: why have a local copy of ojdbc6.jar at all? ojdbc8 should be perfectly fine. Even when running against Oracle 11 ... and the dependency seems to be updated properly.

I also found a build.xml where it's used -- do you still intend to support build with ant?

Otherwise I'd propose to simply get rid both of ojdbc6.jar and build.xml ;-) ...

**Comment by sproket** [comment]
No I'm doing anything with ant anymore. It might work still. I'll remove it at some point. I'll try out the ojdbc8.
