### ISSUE TITLE
Projections

### ISSUE THREAD

**Issue by vicenrico** [sproket/Persism#35]
I don't know whether this is implemented or not, but I haven't found the way.
I have an object whose name is Movie and also a moviesList.
I know I can fetch a list of these movies and , of course, a single movie object. But what I don't know is how to get a list of the movies ids.

Example:
Table movies( int id , String title), ......
I don't want a list of movies with ALL their fields,  nor a single movie object. I want a list that ONLY consists  of the ids of these movies and for the other fields, filled with their default values. Is that possible?. I can load all the objects and afterwards, map these objects to their ids, but I'd like to avoid loading everything.

I've tried the following but is not working:
`List<Movie> moviesIdsList = session.query(Movie.class, sql("SELECT id FROM Movies"));`
It says the object movie was not properly initialized. I though the object would be initialized with default values or something like that. Can you help me?

**Comment by sproket** [comment]
Yes you can. Just select as int or list of Integer

`List<Integer> moviesIdsList = session.query(Integer.class, sql("SELECT id FROM Movies"));`

Hope this helps.

**Comment by vicenrico** [comment]
Yes, I know, but what I want is getting a list of movie objects with only
the id fields preloaded and the rest with their default values, not a list
of integers

**Comment by sproket** [comment]
No, Persism will not let you have incomplete objects.  It's usually not a good idea for the ORM to allow for that because it opens up to lots of null pointer problems. 

You could have a separate class or record with just id, and description and select that. 

```
@NotTable
record MovieInfo(int id, String desc) {
}

`List<MovieInfo> moviesIdsList = session.query(MovieInfo.class), sql("SELECT id,desc FROM Movies"));`

```

If you want to select a specific set of Movie objects by ID you can just skip the sql parameter and just pass the id parameters.

`List<Movie> moviesIdsList = session.query(Movie.class, params(1,2,3,4,5));`
